# fly.toml app configuration file generated for ai-blog-snowy-glitter-4565 on 2025-02-05T18:25:37+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-blog-snowy-glitter-4565'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
